# Generated by Django 4.0.3 on 2022-05-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='rasmlar/playlist_rasm')),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
