# Generated by Django 4.0.3 on 2022-05-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teachers_remove_videodars_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodars',
            name='sana',
            field=models.DateTimeField(auto_now_add=True, default=4.5),
            preserve_default=False,
        ),
    ]
