# Generated by Django 4.0.3 on 2022-05-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_videodars_sana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='sana',
        ),
    ]
