# Generated by Django 4.0.3 on 2022-05-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_teachers_sana'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.RemoveField(
            model_name='videodars',
            name='sana',
        ),
    ]
